version: '3.3'
services:
    couchbase:
        ports:
            - '8091-8093:8091-8093'
            - '11210:11210'
        environment:
            - COUCHBASE_ADMINISTRATOR_USERNAME=admin
            - COUCHBASE_ADMINISTRATOR_PASSWORD=password
        container_name: couchbase
        image: couchbase